"""init

Revision ID: 0fd10f4a7251
Revises: dd33cb03d01f
Create Date: 2022-11-29 16:29:32.789880

"""

# revision identifiers, used by Alembic.
revision = '0fd10f4a7251'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
