"""init

Revision ID: 32dceed53da3
Revises: 81bd42dd7d1c
Create Date: 2022-11-29 16:59:02.321099

"""

# revision identifiers, used by Alembic.
revision = '32dceed53da3'
down_revision = '81bd42dd7d1c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
