"""init

Revision ID: 3c6bda9ed355
Revises: ca84c048473d
Create Date: 2022-11-29 16:54:03.470705

"""

# revision identifiers, used by Alembic.
revision = '3c6bda9ed355'
down_revision = 'ca84c048473d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
