"""init

Revision ID: 545462b17ea5
Revises: 32dceed53da3
Create Date: 2022-11-29 16:59:23.104518

"""

# revision identifiers, used by Alembic.
revision = '545462b17ea5'
down_revision = '32dceed53da3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
