"""init

Revision ID: 5944681aa93b
Revises: 7a479340b497
Create Date: 2022-11-29 21:51:44.132829

"""

# revision identifiers, used by Alembic.
revision = '5944681aa93b'
down_revision = '7a479340b497'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
