"""init

Revision ID: 62ecac209933
Revises: ae4fd926ad7a
Create Date: 2022-11-29 16:35:32.026860

"""

# revision identifiers, used by Alembic.
revision = '62ecac209933'
down_revision = 'ae4fd926ad7a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
