"""init

Revision ID: 6502b84a404b
Revises: 5944681aa93b
Create Date: 2022-11-29 21:57:18.536624

"""

# revision identifiers, used by Alembic.
revision = '6502b84a404b'
down_revision = '5944681aa93b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
