"""init

Revision ID: 7452181b4daa
Revises: 545462b17ea5
Create Date: 2022-11-29 17:11:32.308934

"""

# revision identifiers, used by Alembic.
revision = '7452181b4daa'
down_revision = '545462b17ea5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
