"""init

Revision ID: 7a479340b497
Revises: e8e89d73da37
Create Date: 2022-11-29 21:47:23.829945

"""

# revision identifiers, used by Alembic.
revision = '7a479340b497'
down_revision = 'e8e89d73da37'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
