"""init

Revision ID: 80a16bf0645f
Revises: 62ecac209933
Create Date: 2022-11-29 16:40:32.932210

"""

# revision identifiers, used by Alembic.
revision = '80a16bf0645f'
down_revision = '62ecac209933'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
