"""init

Revision ID: 81bd42dd7d1c
Revises: ce5581e1817f
Create Date: 2022-11-29 16:56:26.841787

"""

# revision identifiers, used by Alembic.
revision = '81bd42dd7d1c'
down_revision = 'ce5581e1817f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
