"""init

Revision ID: 847dcddd7e12
Revises: b8d49c01461c
Create Date: 2022-11-29 23:15:07.884314

"""

# revision identifiers, used by Alembic.
revision = '847dcddd7e12'
down_revision = 'b8d49c01461c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
