"""init

Revision ID: 9fe6178c83eb
Revises: a506b9a7c141
Create Date: 2022-11-29 22:07:24.632263

"""

# revision identifiers, used by Alembic.
revision = '9fe6178c83eb'
down_revision = 'a506b9a7c141'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
