"""init

Revision ID: a0d304deabe6
Revises: a3a46ff55d17
Create Date: 2022-11-29 18:59:16.060367

"""

# revision identifiers, used by Alembic.
revision = 'a0d304deabe6'
down_revision = 'a3a46ff55d17'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
