"""init

Revision ID: a3a46ff55d17
Revises: 7452181b4daa
Create Date: 2022-11-29 18:55:42.354854

"""

# revision identifiers, used by Alembic.
revision = 'a3a46ff55d17'
down_revision = '7452181b4daa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
