"""init

Revision ID: a506b9a7c141
Revises: 6502b84a404b
Create Date: 2022-11-29 21:59:58.056258

"""

# revision identifiers, used by Alembic.
revision = 'a506b9a7c141'
down_revision = '6502b84a404b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
