"""init

Revision ID: ae4fd926ad7a
Revises: 0fd10f4a7251
Create Date: 2022-11-29 16:34:19.409654

"""

# revision identifiers, used by Alembic.
revision = 'ae4fd926ad7a'
down_revision = '0fd10f4a7251'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
