"""init

Revision ID: b8d49c01461c
Revises: 9fe6178c83eb
Create Date: 2022-11-29 22:41:47.235181

"""

# revision identifiers, used by Alembic.
revision = 'b8d49c01461c'
down_revision = '9fe6178c83eb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
