"""init

Revision ID: c71d0f40b3b6
Revises: 80a16bf0645f
Create Date: 2022-11-29 16:46:28.971482

"""

# revision identifiers, used by Alembic.
revision = 'c71d0f40b3b6'
down_revision = '80a16bf0645f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
