"""init

Revision ID: ca84c048473d
Revises: c71d0f40b3b6
Create Date: 2022-11-29 16:52:37.053539

"""

# revision identifiers, used by Alembic.
revision = 'ca84c048473d'
down_revision = 'c71d0f40b3b6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
