"""init

Revision ID: ce5581e1817f
Revises: 3c6bda9ed355
Create Date: 2022-11-29 16:56:08.574812

"""

# revision identifiers, used by Alembic.
revision = 'ce5581e1817f'
down_revision = '3c6bda9ed355'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
