"""init

Revision ID: d44a6912cd5d
Revises: 847dcddd7e12
Create Date: 2022-11-29 23:34:51.708445

"""

# revision identifiers, used by Alembic.
revision = 'd44a6912cd5d'
down_revision = '847dcddd7e12'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
