"""init

Revision ID: e8e89d73da37
Revises: a0d304deabe6
Create Date: 2022-11-29 19:12:52.169560

"""

# revision identifiers, used by Alembic.
revision = 'e8e89d73da37'
down_revision = 'a0d304deabe6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
